---
title: "Social Mobility: Pre-Processing"
subtitle: "Step 03: Feature Points to geoJSON"
author: "Michael Lopez"
date: "`r format(Sys.Date(), '%B, %d, %Y'`"
output: 
  github_document: default
    toc: true
    number_sections: true
    toc_float: true
    theme: pagedown::architect
    code_folding: show
---

```{r setup, include = FALSE, echo = FALSE}
rm(list=ls(all=TRUE))
knitr::opts_knit$set(root.dir = 'E:/CPAL Dropbox')
#knitr::opts_knit$set(root.dir = 'C:/Users/OwenWilson-Chavez/CPAL Dropbox')
getwd()
library(tidyverse)
library(rio)
library(tigris)
library(sf)
library(lubridate)
```

```{r directory test}
getwd()
```

```{r, echo = FALSE}
#import geography comparison shape file
zip.sh <- st_read("C:/Users/Michael Lopez/Documents/GitHub/Social-Mobility/Data/Reference Geographies/Shapefiles/sm_zcta.shp")

#import feature shape files
snap.sh <- st_read("Data Library/USDA/GIS/SNAP_Store_Locations_TX_Dec2020.shp")
banks.sh <- st_read("Data Library/01_Data Update Projects/Dallas Features/Verification/Banks.shp") 
comcen.sh <- st_read("Data Library/NCTCOG/CommunityCenters.shp")
comhealth.sh <- st_read("Data Library/Miscellaneous/Community Health Clinics/CommunityHealthClincs_June2020.shp")
creditunions.sh <- st_read("Data Library/Google/GIS/Shapefiles/CreditUnions_Dec2020.shp") 
supermarket.sh <- st_read("Data Library/Miscellaneous/Grocery Stores/FoodandGrocery_DallasCounty_July2020.shp")
pharmacies.sh <-st_read("Data Library/Texas State Board of Pharmacy/GIS/TBSP_NTX_Dec2020.shp")
libraries.sh <- st_read("Data Library/City of Dallas/02_Boundaries and Features/Libraries.shp")
librariesTX.sh <- st_read("Data Library/Texas Public Libraries/Texas_Public_Libraries.shp")
schools.sh <- st_read("Data Library/Texas Education Agency/GIS/Current_Schools_2020-2021.shp")
schoolsprivate.sh <- st_read("Data Library/Texas Private School Accreditation Commission/TexasPrivateSchools_Feb2021.shp")
wic.sh <- st_read("Data Library/Google/GIS/Shapefiles/WIC_Locations_Dec2020.shp") 
childcare.sh <- st_read("Data Library/Texas Department of Family and Protective Services/SubsidyAccepting_ChildcareCenters_Feb2020.shp")
childcareAll.sh <- st_read("Data Library/Texas Department of Family and Protective Services/All_ChildcareCenters_Feb2020.shp")
childcareAll.sh <- as.data.frame(childcareAll.sh) %>%
  select(-geometry) %>%
  mutate(x_coor = X,
         y_coor = Y) %>%
  st_as_sf(x = ., coords = c(x = "X", y = "Y"),
                        crs = "+proj=longlat +datum=WGS84 +no_defs")
```

```{r}
#edit shape files to only contain necessary columns
snap.join <- snap.sh %>%
  mutate(Display = "SNAP Retailer",
         variable = "snap") %>%
  rename(Name = Store_Name) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(snap.sh)

banks.join <- banks.sh %>%
  st_transform(crs = 4326) %>%
  mutate(Display = "Bank",
         variable = "bank") %>%
  rename(Longitude = X,
         Latitude = Y) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(banks.sh)

comcen.join <- comcen.sh %>%
  st_transform(crs = 4326) %>%
  mutate(Longitude = st_coordinates(.)[,1],
         Latitude = st_coordinates(.)[,2],
         Display = "Community Center",
         variable = "comcen") %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(comcen.sh)

comhealth.join <- comhealth.sh %>%
  mutate(Display = "Community Health Clinic",
         variable = "comhel") %>%
  rename(Name = USER_Clini,
         Address = StAddr,
         Longitude = X,
         Latitude = Y) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(comhealth.sh)

creditunions.join <- creditunions.sh %>%
  mutate(Longitude = st_coordinates(.)[,1],
         Latitude = st_coordinates(.)[,2],
         Display = "Credit Union",
         City = word(plcs_dd,-1),
         variable = "crunion") %>%
  rename(Name = plcs_nm,
         Address = plcs_dd) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
st_crs(creditunions.join) = 4326
rm(creditunions.sh)

supermarket.join <- supermarket.sh %>%
  mutate(Display = "Supermarket",
         variable = "market") %>%
  rename(Name = BusinessNa,
         Address = Bus_Addres) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(supermarket.sh)

pharmacies.join <- pharmacies.sh %>%
  mutate(Display = "Pharmacy",
         variable = "pharm") %>%
  rename(Address = StAddr,
         Longitude = X,
         Latitude = Y,
         Name = USER_phy_n) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(pharmacies.sh)

librariesTX.join <- librariesTX.sh %>%
  select(USER_Libra, USER_Addre, X, Y, USER_City) %>%
  mutate(Display = "Library",
         variable = "lib") %>%
  rename(Name = USER_Libra,
         Address = USER_Addre,
         City = USER_City,
         Longitude = X,
         Latitude = Y) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(librariesTX.sh)

libraries.join <- libraries.sh %>%
  mutate(Display = "Library",
         City = "Dallas",
         variable = "lib") %>%
  rename(Name = LIBRARY,
         Address = ADDRESS,
         Longitude = X,
         Latitude = Y) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry) %>%
  full_join(., as.data.frame(librariesTX.join))
rm(libraries.sh)
rm(librariesTX.join)

schools.join <- schools.sh %>%
  rename(Address = StAddr,
         Name = School_Nam,
         Longitude = X,
         Latitude = Y,
         District_Type = District_T,
         Grade_Level = Grade_Leve
         ) %>%
  mutate(Display = ifelse(District_Type == "INDEPENDENT" & Grade_Level == "High School", "Independent High School",
                          ifelse(District_Type == "INDEPENDENT" & Grade_Level %in% c("Middle", "Junior High"), "Independent Middle School",
                                 ifelse(District_Type == "INDEPENDENT" & Grade_Level %in% c("Elementary", "Elementary/Secondary"), "Independent Elementary School",
                                        ifelse(District_Type == "CHARTER" & Grade_Level == "High School", "Charter High School",
                                               ifelse(District_Type == "CHARTER" & Grade_Level %in% c("Middle", "Junior High"), "Charter Middle School",
                                                      ifelse(District_Type == "CHARTER" & Grade_Level %in% c("Elementary", "Elementary/Secondary"), "Charter Elementary School",
                                                             "Other School")))))),
         variable = ifelse(Display == "Independent High School", "ihs",
                          ifelse(Display == "Independent Middle School", "ims",
                                 ifelse(Display == "Independent Elementary School", "ies",
                                        ifelse(Display == "Charter High School", "chs",
                                               ifelse(Display == "Charter Middle School", "cms",
                                                      ifelse(Display == "Charter Elementary School", "ces",
                                                             "os"))))))) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry) %>%
  filter(variable != "os")
rm(schools.sh)

schoolsprivate.join <- schoolsprivate.sh %>%
  mutate(Display = "Private School",
         variable = "prs",
         Address = ShortLabel) %>%
  rename(Longitude = X,
         Latitude = Y,
         Name = USER_Schoo) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)

rm(schoolsprivate.sh)

wic.join <- wic.sh %>%
  mutate(Longitude = st_coordinates(.)[,1],
         Latitude = st_coordinates(.)[,2],
         Display = "WIC Clinic",
         City = word(plcs_dd,-1),
         variable = "wic") %>%
  rename(Name = plcs_nm,
         Address = plcs_dd) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
st_crs(wic.join) = 4326
rm(wic.sh)

childcare.join <- childcare.sh %>%
  mutate(Display = "Subsidized Childcare Center",
         City = word(Address,-4),
         variable = "scc") %>%
  rename(Longitude = X,
         Latitude = Y) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(childcare.sh)

childcareAll.join <- childcareAll.sh %>%
  filter(USER_SubsY == "N") %>%
  mutate(Display = "Childcare Center",
         City = str_to_title(USER_COUNT),
         variable = "uscc") %>%
  rename(Longitude = x_coor,
         Latitude = y_coor,
         Name = USER_Name,
         Address = USER_Addre) %>%
  select(Display, variable, Name, Address, City, Longitude, Latitude, geometry)
rm(childcareAll.sh)
```

```{r}
#select points within geography of interest
snap.zip <- snap.join[zip.sh, ]

banks.zip <- banks.join[zip.sh, ]

comcen.zip <- comcen.join[zip.sh, ]

comhealth.zip <- comhealth.join[zip.sh, ]

creditunions.zip <- creditunions.join[zip.sh, ]

supermarket.zip <- supermarket.join[zip.sh, ]

pharmacies.zip <- pharmacies.join[zip.sh, ]

libraries.zip <- libraries.join[zip.sh, ]

schools.zip <- schools.join[zip.sh, ]

schoolsprivate.zip <- schoolsprivate.join[zip.sh, ]

wic.zip <- wic.join[zip.sh, ]

childcare.zip <- childcare.join[zip.sh, ]

childcareAll.zip <- childcareAll.join[zip.sh, ]
```

```{r}
#join all files into one
featureset <- rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(rbind(
                    snap.zip, banks.zip), comcen.zip), comhealth.zip), creditunions.zip), supermarket.zip), pharmacies.zip), libraries.zip), schools.zip), schoolsprivate.zip), wic.zip), childcare.zip), childcareAll.zip)

featureset <- featureset %>%
  mutate(FID = 1:n(),
         Name = str_to_title(Name)) %>%
  select(FID, everything())
```


```{r}
#export to geojson
geojsonio::geojson_write(featureset, file = "C:/Users/Michael Lopez/Documents/GitHub/Social-Mobility/Data/geojson/sm_featureset.geojson")
```

