name: Gzip map data files and copy to aws

# Triggers the workflow on push to testing, staging, or production.
on:
  push:
    branches:
      - testing
      - staging
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2 # default
          verbose: true # default
      - id: check-out-branch
        uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Gzip data directory
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
          tree .
          cp -r ./Data/geojson gzip
          cp ./DataDictionary.csv gzip
          ls -la gzip
          gzip -r gzip
          tree gzip
          aws s3 cp --recursive ./gzip s3://untd-data/${GITHUB_REF##*/}/ \
            --acl=public-read \
            --content-encoding=gzip \
            --region=us-east-1 \
            --cache-control max-age=2628000
